#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV_ThucTap
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLTV_ThucTap")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCT_PHIEUMUON(CT_PHIEUMUON instance);
    partial void UpdateCT_PHIEUMUON(CT_PHIEUMUON instance);
    partial void DeleteCT_PHIEUMUON(CT_PHIEUMUON instance);
    partial void InsertNHA_XUAT_BAN(NHA_XUAT_BAN instance);
    partial void UpdateNHA_XUAT_BAN(NHA_XUAT_BAN instance);
    partial void DeleteNHA_XUAT_BAN(NHA_XUAT_BAN instance);
    partial void InsertNHAN_VIEN(NHAN_VIEN instance);
    partial void UpdateNHAN_VIEN(NHAN_VIEN instance);
    partial void DeleteNHAN_VIEN(NHAN_VIEN instance);
    partial void InsertPHIEU_MUON(PHIEU_MUON instance);
    partial void UpdatePHIEU_MUON(PHIEU_MUON instance);
    partial void DeletePHIEU_MUON(PHIEU_MUON instance);
    partial void InsertSACH(SACH instance);
    partial void UpdateSACH(SACH instance);
    partial void DeleteSACH(SACH instance);
    partial void InsertSINH_VIEN(SINH_VIEN instance);
    partial void UpdateSINH_VIEN(SINH_VIEN instance);
    partial void DeleteSINH_VIEN(SINH_VIEN instance);
    partial void InsertTAC_GIA1(TAC_GIA1 instance);
    partial void UpdateTAC_GIA1(TAC_GIA1 instance);
    partial void DeleteTAC_GIA1(TAC_GIA1 instance);
    partial void InsertTHE_LOAI(THE_LOAI instance);
    partial void UpdateTHE_LOAI(THE_LOAI instance);
    partial void DeleteTHE_LOAI(THE_LOAI instance);
    partial void InsertTRA_SACH(TRA_SACH instance);
    partial void UpdateTRA_SACH(TRA_SACH instance);
    partial void DeleteTRA_SACH(TRA_SACH instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::QLTV_ThucTap.Properties.Settings.Default.QLTV_ThucTapConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CT_PHIEUMUON> CT_PHIEUMUONs
		{
			get
			{
				return this.GetTable<CT_PHIEUMUON>();
			}
		}
		
		public System.Data.Linq.Table<NHA_XUAT_BAN> NHA_XUAT_BANs
		{
			get
			{
				return this.GetTable<NHA_XUAT_BAN>();
			}
		}
		
		public System.Data.Linq.Table<NHAN_VIEN> NHAN_VIENs
		{
			get
			{
				return this.GetTable<NHAN_VIEN>();
			}
		}
		
		public System.Data.Linq.Table<PHIEU_MUON> PHIEU_MUONs
		{
			get
			{
				return this.GetTable<PHIEU_MUON>();
			}
		}
		
		public System.Data.Linq.Table<SACH> SACHes
		{
			get
			{
				return this.GetTable<SACH>();
			}
		}
		
		public System.Data.Linq.Table<SINH_VIEN> SINH_VIENs
		{
			get
			{
				return this.GetTable<SINH_VIEN>();
			}
		}
		
		public System.Data.Linq.Table<TAC_GIA1> TAC_GIA1s
		{
			get
			{
				return this.GetTable<TAC_GIA1>();
			}
		}
		
		public System.Data.Linq.Table<THE_LOAI> THE_LOAIs
		{
			get
			{
				return this.GetTable<THE_LOAI>();
			}
		}
		
		public System.Data.Linq.Table<TRA_SACH> TRA_SACHes
		{
			get
			{
				return this.GetTable<TRA_SACH>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_PHIEUMUON")]
	public partial class CT_PHIEUMUON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _maSV;
		
		private int _maPhieu;
		
		private System.Nullable<int> _maSach;
		
		private System.Nullable<System.DateTime> _ngayTra;
		
		private string _tinhTrang;
		
		private System.Nullable<System.DateTime> _ngayMuon;
		
		private System.Nullable<int> _soLuong;
		
		private int _id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaSVChanging(System.Nullable<int> value);
    partial void OnmaSVChanged();
    partial void OnmaPhieuChanging(int value);
    partial void OnmaPhieuChanged();
    partial void OnmaSachChanging(System.Nullable<int> value);
    partial void OnmaSachChanged();
    partial void OnngayTraChanging(System.Nullable<System.DateTime> value);
    partial void OnngayTraChanged();
    partial void OntinhTrangChanging(string value);
    partial void OntinhTrangChanged();
    partial void OnngayMuonChanging(System.Nullable<System.DateTime> value);
    partial void OnngayMuonChanged();
    partial void OnsoLuongChanging(System.Nullable<int> value);
    partial void OnsoLuongChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    #endregion
		
		public CT_PHIEUMUON()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSV", DbType="Int")]
		public System.Nullable<int> maSV
		{
			get
			{
				return this._maSV;
			}
			set
			{
				if ((this._maSV != value))
				{
					this.OnmaSVChanging(value);
					this.SendPropertyChanging();
					this._maSV = value;
					this.SendPropertyChanged("maSV");
					this.OnmaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhieu", DbType="Int NOT NULL")]
		public int maPhieu
		{
			get
			{
				return this._maPhieu;
			}
			set
			{
				if ((this._maPhieu != value))
				{
					this.OnmaPhieuChanging(value);
					this.SendPropertyChanging();
					this._maPhieu = value;
					this.SendPropertyChanged("maPhieu");
					this.OnmaPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSach", DbType="Int")]
		public System.Nullable<int> maSach
		{
			get
			{
				return this._maSach;
			}
			set
			{
				if ((this._maSach != value))
				{
					this.OnmaSachChanging(value);
					this.SendPropertyChanging();
					this._maSach = value;
					this.SendPropertyChanged("maSach");
					this.OnmaSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayTra", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayTra
		{
			get
			{
				return this._ngayTra;
			}
			set
			{
				if ((this._ngayTra != value))
				{
					this.OnngayTraChanging(value);
					this.SendPropertyChanging();
					this._ngayTra = value;
					this.SendPropertyChanged("ngayTra");
					this.OnngayTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhTrang", DbType="NVarChar(50)")]
		public string tinhTrang
		{
			get
			{
				return this._tinhTrang;
			}
			set
			{
				if ((this._tinhTrang != value))
				{
					this.OntinhTrangChanging(value);
					this.SendPropertyChanging();
					this._tinhTrang = value;
					this.SendPropertyChanged("tinhTrang");
					this.OntinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayMuon", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayMuon
		{
			get
			{
				return this._ngayMuon;
			}
			set
			{
				if ((this._ngayMuon != value))
				{
					this.OnngayMuonChanging(value);
					this.SendPropertyChanging();
					this._ngayMuon = value;
					this.SendPropertyChanged("ngayMuon");
					this.OnngayMuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int")]
		public System.Nullable<int> soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHA_XUAT_BAN")]
	public partial class NHA_XUAT_BAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maNXB;
		
		private string _tenNXB;
		
		private string _diachiNXB;
		
		private string _dienthoaiNXB;
		
		private string _websiteNXB;
		
		private string _GhiChu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNXBChanging(int value);
    partial void OnmaNXBChanged();
    partial void OntenNXBChanging(string value);
    partial void OntenNXBChanged();
    partial void OndiachiNXBChanging(string value);
    partial void OndiachiNXBChanged();
    partial void OndienthoaiNXBChanging(string value);
    partial void OndienthoaiNXBChanged();
    partial void OnwebsiteNXBChanging(string value);
    partial void OnwebsiteNXBChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public NHA_XUAT_BAN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNXB", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maNXB
		{
			get
			{
				return this._maNXB;
			}
			set
			{
				if ((this._maNXB != value))
				{
					this.OnmaNXBChanging(value);
					this.SendPropertyChanging();
					this._maNXB = value;
					this.SendPropertyChanged("maNXB");
					this.OnmaNXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNXB", DbType="NVarChar(50)")]
		public string tenNXB
		{
			get
			{
				return this._tenNXB;
			}
			set
			{
				if ((this._tenNXB != value))
				{
					this.OntenNXBChanging(value);
					this.SendPropertyChanging();
					this._tenNXB = value;
					this.SendPropertyChanged("tenNXB");
					this.OntenNXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachiNXB", DbType="NVarChar(100)")]
		public string diachiNXB
		{
			get
			{
				return this._diachiNXB;
			}
			set
			{
				if ((this._diachiNXB != value))
				{
					this.OndiachiNXBChanging(value);
					this.SendPropertyChanging();
					this._diachiNXB = value;
					this.SendPropertyChanged("diachiNXB");
					this.OndiachiNXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dienthoaiNXB", DbType="Char(11)")]
		public string dienthoaiNXB
		{
			get
			{
				return this._dienthoaiNXB;
			}
			set
			{
				if ((this._dienthoaiNXB != value))
				{
					this.OndienthoaiNXBChanging(value);
					this.SendPropertyChanging();
					this._dienthoaiNXB = value;
					this.SendPropertyChanged("dienthoaiNXB");
					this.OndienthoaiNXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_websiteNXB", DbType="Char(100)")]
		public string websiteNXB
		{
			get
			{
				return this._websiteNXB;
			}
			set
			{
				if ((this._websiteNXB != value))
				{
					this.OnwebsiteNXBChanging(value);
					this.SendPropertyChanging();
					this._websiteNXB = value;
					this.SendPropertyChanged("websiteNXB");
					this.OnwebsiteNXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(50)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHAN_VIEN")]
	public partial class NHAN_VIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maNV;
		
		private string _tenNV;
		
		private string _gioiTinhNV;
		
		private System.Nullable<System.DateTime> _ngaySinhNV;
		
		private string _diaChiNV;
		
		private System.Nullable<System.DateTime> _ngayVaoLam;
		
		private string _dienThoaiNV;
		
		private string _matKhau;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNVChanging(int value);
    partial void OnmaNVChanged();
    partial void OntenNVChanging(string value);
    partial void OntenNVChanged();
    partial void OngioiTinhNVChanging(string value);
    partial void OngioiTinhNVChanged();
    partial void OnngaySinhNVChanging(System.Nullable<System.DateTime> value);
    partial void OnngaySinhNVChanged();
    partial void OndiaChiNVChanging(string value);
    partial void OndiaChiNVChanged();
    partial void OnngayVaoLamChanging(System.Nullable<System.DateTime> value);
    partial void OnngayVaoLamChanged();
    partial void OndienThoaiNVChanging(string value);
    partial void OndienThoaiNVChanged();
    partial void OnmatKhauChanging(string value);
    partial void OnmatKhauChanged();
    #endregion
		
		public NHAN_VIEN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNV", DbType="NVarChar(50)")]
		public string tenNV
		{
			get
			{
				return this._tenNV;
			}
			set
			{
				if ((this._tenNV != value))
				{
					this.OntenNVChanging(value);
					this.SendPropertyChanging();
					this._tenNV = value;
					this.SendPropertyChanged("tenNV");
					this.OntenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinhNV", DbType="Char(10)")]
		public string gioiTinhNV
		{
			get
			{
				return this._gioiTinhNV;
			}
			set
			{
				if ((this._gioiTinhNV != value))
				{
					this.OngioiTinhNVChanging(value);
					this.SendPropertyChanging();
					this._gioiTinhNV = value;
					this.SendPropertyChanged("gioiTinhNV");
					this.OngioiTinhNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinhNV", DbType="Date")]
		public System.Nullable<System.DateTime> ngaySinhNV
		{
			get
			{
				return this._ngaySinhNV;
			}
			set
			{
				if ((this._ngaySinhNV != value))
				{
					this.OnngaySinhNVChanging(value);
					this.SendPropertyChanging();
					this._ngaySinhNV = value;
					this.SendPropertyChanged("ngaySinhNV");
					this.OnngaySinhNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChiNV", DbType="NVarChar(100)")]
		public string diaChiNV
		{
			get
			{
				return this._diaChiNV;
			}
			set
			{
				if ((this._diaChiNV != value))
				{
					this.OndiaChiNVChanging(value);
					this.SendPropertyChanging();
					this._diaChiNV = value;
					this.SendPropertyChanged("diaChiNV");
					this.OndiaChiNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayVaoLam", DbType="Date")]
		public System.Nullable<System.DateTime> ngayVaoLam
		{
			get
			{
				return this._ngayVaoLam;
			}
			set
			{
				if ((this._ngayVaoLam != value))
				{
					this.OnngayVaoLamChanging(value);
					this.SendPropertyChanging();
					this._ngayVaoLam = value;
					this.SendPropertyChanged("ngayVaoLam");
					this.OnngayVaoLamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dienThoaiNV", DbType="VarChar(50)")]
		public string dienThoaiNV
		{
			get
			{
				return this._dienThoaiNV;
			}
			set
			{
				if ((this._dienThoaiNV != value))
				{
					this.OndienThoaiNVChanging(value);
					this.SendPropertyChanging();
					this._dienThoaiNV = value;
					this.SendPropertyChanged("dienThoaiNV");
					this.OndienThoaiNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matKhau", DbType="NVarChar(50)")]
		public string matKhau
		{
			get
			{
				return this._matKhau;
			}
			set
			{
				if ((this._matKhau != value))
				{
					this.OnmatKhauChanging(value);
					this.SendPropertyChanging();
					this._matKhau = value;
					this.SendPropertyChanged("matKhau");
					this.OnmatKhauChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEU_MUON")]
	public partial class PHIEU_MUON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maPhieu;
		
		private System.Nullable<int> _maSV;
		
		private System.Nullable<int> _maNV;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaPhieuChanging(int value);
    partial void OnmaPhieuChanged();
    partial void OnmaSVChanging(System.Nullable<int> value);
    partial void OnmaSVChanged();
    partial void OnmaNVChanging(System.Nullable<int> value);
    partial void OnmaNVChanged();
    #endregion
		
		public PHIEU_MUON()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhieu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maPhieu
		{
			get
			{
				return this._maPhieu;
			}
			set
			{
				if ((this._maPhieu != value))
				{
					this.OnmaPhieuChanging(value);
					this.SendPropertyChanging();
					this._maPhieu = value;
					this.SendPropertyChanged("maPhieu");
					this.OnmaPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSV", DbType="Int")]
		public System.Nullable<int> maSV
		{
			get
			{
				return this._maSV;
			}
			set
			{
				if ((this._maSV != value))
				{
					this.OnmaSVChanging(value);
					this.SendPropertyChanging();
					this._maSV = value;
					this.SendPropertyChanged("maSV");
					this.OnmaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="Int")]
		public System.Nullable<int> maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SACH")]
	public partial class SACH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maSach;
		
		private string _tenSach;
		
		private System.Nullable<double> _gia;
		
		private System.Nullable<int> _soLuong;
		
		private System.Nullable<int> _maNXB;
		
		private System.Nullable<int> _maTL;
		
		private System.Nullable<int> _soLuongTon;
		
		private System.Nullable<int> _maTG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaSachChanging(int value);
    partial void OnmaSachChanged();
    partial void OntenSachChanging(string value);
    partial void OntenSachChanged();
    partial void OngiaChanging(System.Nullable<double> value);
    partial void OngiaChanged();
    partial void OnsoLuongChanging(System.Nullable<int> value);
    partial void OnsoLuongChanged();
    partial void OnmaNXBChanging(System.Nullable<int> value);
    partial void OnmaNXBChanged();
    partial void OnmaTLChanging(System.Nullable<int> value);
    partial void OnmaTLChanged();
    partial void OnsoLuongTonChanging(System.Nullable<int> value);
    partial void OnsoLuongTonChanged();
    partial void OnmaTGChanging(System.Nullable<int> value);
    partial void OnmaTGChanged();
    #endregion
		
		public SACH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSach", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maSach
		{
			get
			{
				return this._maSach;
			}
			set
			{
				if ((this._maSach != value))
				{
					this.OnmaSachChanging(value);
					this.SendPropertyChanging();
					this._maSach = value;
					this.SendPropertyChanged("maSach");
					this.OnmaSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenSach", DbType="NVarChar(50)")]
		public string tenSach
		{
			get
			{
				return this._tenSach;
			}
			set
			{
				if ((this._tenSach != value))
				{
					this.OntenSachChanging(value);
					this.SendPropertyChanging();
					this._tenSach = value;
					this.SendPropertyChanged("tenSach");
					this.OntenSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Float")]
		public System.Nullable<double> gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int")]
		public System.Nullable<int> soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNXB", DbType="Int")]
		public System.Nullable<int> maNXB
		{
			get
			{
				return this._maNXB;
			}
			set
			{
				if ((this._maNXB != value))
				{
					this.OnmaNXBChanging(value);
					this.SendPropertyChanging();
					this._maNXB = value;
					this.SendPropertyChanged("maNXB");
					this.OnmaNXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maTL", DbType="Int")]
		public System.Nullable<int> maTL
		{
			get
			{
				return this._maTL;
			}
			set
			{
				if ((this._maTL != value))
				{
					this.OnmaTLChanging(value);
					this.SendPropertyChanging();
					this._maTL = value;
					this.SendPropertyChanged("maTL");
					this.OnmaTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuongTon", DbType="Int")]
		public System.Nullable<int> soLuongTon
		{
			get
			{
				return this._soLuongTon;
			}
			set
			{
				if ((this._soLuongTon != value))
				{
					this.OnsoLuongTonChanging(value);
					this.SendPropertyChanging();
					this._soLuongTon = value;
					this.SendPropertyChanged("soLuongTon");
					this.OnsoLuongTonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maTG", DbType="Int")]
		public System.Nullable<int> maTG
		{
			get
			{
				return this._maTG;
			}
			set
			{
				if ((this._maTG != value))
				{
					this.OnmaTGChanging(value);
					this.SendPropertyChanging();
					this._maTG = value;
					this.SendPropertyChanged("maTG");
					this.OnmaTGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SINH_VIEN")]
	public partial class SINH_VIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maSV;
		
		private string _hotenSV;
		
		private string _gioiTinhSV;
		
		private System.Nullable<System.DateTime> _ngaysinhSV;
		
		private string _lopSV;
		
		private System.Nullable<System.DateTime> _ngayLamThe;
		
		private System.Nullable<System.DateTime> _ngayHetHan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaSVChanging(int value);
    partial void OnmaSVChanged();
    partial void OnhotenSVChanging(string value);
    partial void OnhotenSVChanged();
    partial void OngioiTinhSVChanging(string value);
    partial void OngioiTinhSVChanged();
    partial void OnngaysinhSVChanging(System.Nullable<System.DateTime> value);
    partial void OnngaysinhSVChanged();
    partial void OnlopSVChanging(string value);
    partial void OnlopSVChanged();
    partial void OnngayLamTheChanging(System.Nullable<System.DateTime> value);
    partial void OnngayLamTheChanged();
    partial void OnngayHetHanChanging(System.Nullable<System.DateTime> value);
    partial void OnngayHetHanChanged();
    #endregion
		
		public SINH_VIEN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSV", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maSV
		{
			get
			{
				return this._maSV;
			}
			set
			{
				if ((this._maSV != value))
				{
					this.OnmaSVChanging(value);
					this.SendPropertyChanging();
					this._maSV = value;
					this.SendPropertyChanged("maSV");
					this.OnmaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hotenSV", DbType="NVarChar(50)")]
		public string hotenSV
		{
			get
			{
				return this._hotenSV;
			}
			set
			{
				if ((this._hotenSV != value))
				{
					this.OnhotenSVChanging(value);
					this.SendPropertyChanging();
					this._hotenSV = value;
					this.SendPropertyChanged("hotenSV");
					this.OnhotenSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinhSV", DbType="Char(10)")]
		public string gioiTinhSV
		{
			get
			{
				return this._gioiTinhSV;
			}
			set
			{
				if ((this._gioiTinhSV != value))
				{
					this.OngioiTinhSVChanging(value);
					this.SendPropertyChanging();
					this._gioiTinhSV = value;
					this.SendPropertyChanged("gioiTinhSV");
					this.OngioiTinhSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinhSV", DbType="Date")]
		public System.Nullable<System.DateTime> ngaysinhSV
		{
			get
			{
				return this._ngaysinhSV;
			}
			set
			{
				if ((this._ngaysinhSV != value))
				{
					this.OnngaysinhSVChanging(value);
					this.SendPropertyChanging();
					this._ngaysinhSV = value;
					this.SendPropertyChanged("ngaysinhSV");
					this.OnngaysinhSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lopSV", DbType="Char(20)")]
		public string lopSV
		{
			get
			{
				return this._lopSV;
			}
			set
			{
				if ((this._lopSV != value))
				{
					this.OnlopSVChanging(value);
					this.SendPropertyChanging();
					this._lopSV = value;
					this.SendPropertyChanged("lopSV");
					this.OnlopSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayLamThe", DbType="Date")]
		public System.Nullable<System.DateTime> ngayLamThe
		{
			get
			{
				return this._ngayLamThe;
			}
			set
			{
				if ((this._ngayLamThe != value))
				{
					this.OnngayLamTheChanging(value);
					this.SendPropertyChanging();
					this._ngayLamThe = value;
					this.SendPropertyChanged("ngayLamThe");
					this.OnngayLamTheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayHetHan", DbType="Date")]
		public System.Nullable<System.DateTime> ngayHetHan
		{
			get
			{
				return this._ngayHetHan;
			}
			set
			{
				if ((this._ngayHetHan != value))
				{
					this.OnngayHetHanChanging(value);
					this.SendPropertyChanging();
					this._ngayHetHan = value;
					this.SendPropertyChanged("ngayHetHan");
					this.OnngayHetHanChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAC_GIA1")]
	public partial class TAC_GIA1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maTG;
		
		private string _tenTG;
		
		private string _GhiChu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaTGChanging(int value);
    partial void OnmaTGChanged();
    partial void OntenTGChanging(string value);
    partial void OntenTGChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public TAC_GIA1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maTG", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maTG
		{
			get
			{
				return this._maTG;
			}
			set
			{
				if ((this._maTG != value))
				{
					this.OnmaTGChanging(value);
					this.SendPropertyChanging();
					this._maTG = value;
					this.SendPropertyChanged("maTG");
					this.OnmaTGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenTG", DbType="NVarChar(50)")]
		public string tenTG
		{
			get
			{
				return this._tenTG;
			}
			set
			{
				if ((this._tenTG != value))
				{
					this.OntenTGChanging(value);
					this.SendPropertyChanging();
					this._tenTG = value;
					this.SendPropertyChanged("tenTG");
					this.OntenTGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(50)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THE_LOAI")]
	public partial class THE_LOAI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maTL;
		
		private string _tenTL;
		
		private string _GhiChu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaTLChanging(int value);
    partial void OnmaTLChanged();
    partial void OntenTLChanging(string value);
    partial void OntenTLChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public THE_LOAI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maTL", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maTL
		{
			get
			{
				return this._maTL;
			}
			set
			{
				if ((this._maTL != value))
				{
					this.OnmaTLChanging(value);
					this.SendPropertyChanging();
					this._maTL = value;
					this.SendPropertyChanged("maTL");
					this.OnmaTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenTL", DbType="NVarChar(50)")]
		public string tenTL
		{
			get
			{
				return this._tenTL;
			}
			set
			{
				if ((this._tenTL != value))
				{
					this.OntenTLChanging(value);
					this.SendPropertyChanging();
					this._tenTL = value;
					this.SendPropertyChanged("tenTL");
					this.OntenTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(MAX)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRA_SACH")]
	public partial class TRA_SACH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maPhieu;
		
		private System.Nullable<int> _maSach;
		
		private System.Nullable<int> _maNV;
		
		private System.Nullable<System.DateTime> _ngayTra;
		
		private string _tenSach;
		
		private string _tinhTrang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaPhieuChanging(int value);
    partial void OnmaPhieuChanged();
    partial void OnmaSachChanging(System.Nullable<int> value);
    partial void OnmaSachChanged();
    partial void OnmaNVChanging(System.Nullable<int> value);
    partial void OnmaNVChanged();
    partial void OnngayTraChanging(System.Nullable<System.DateTime> value);
    partial void OnngayTraChanged();
    partial void OntenSachChanging(string value);
    partial void OntenSachChanged();
    partial void OntinhTrangChanging(string value);
    partial void OntinhTrangChanged();
    #endregion
		
		public TRA_SACH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhieu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maPhieu
		{
			get
			{
				return this._maPhieu;
			}
			set
			{
				if ((this._maPhieu != value))
				{
					this.OnmaPhieuChanging(value);
					this.SendPropertyChanging();
					this._maPhieu = value;
					this.SendPropertyChanged("maPhieu");
					this.OnmaPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSach", DbType="Int")]
		public System.Nullable<int> maSach
		{
			get
			{
				return this._maSach;
			}
			set
			{
				if ((this._maSach != value))
				{
					this.OnmaSachChanging(value);
					this.SendPropertyChanging();
					this._maSach = value;
					this.SendPropertyChanged("maSach");
					this.OnmaSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="Int")]
		public System.Nullable<int> maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayTra", DbType="Date")]
		public System.Nullable<System.DateTime> ngayTra
		{
			get
			{
				return this._ngayTra;
			}
			set
			{
				if ((this._ngayTra != value))
				{
					this.OnngayTraChanging(value);
					this.SendPropertyChanging();
					this._ngayTra = value;
					this.SendPropertyChanged("ngayTra");
					this.OnngayTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenSach", DbType="NVarChar(50)")]
		public string tenSach
		{
			get
			{
				return this._tenSach;
			}
			set
			{
				if ((this._tenSach != value))
				{
					this.OntenSachChanging(value);
					this.SendPropertyChanging();
					this._tenSach = value;
					this.SendPropertyChanged("tenSach");
					this.OntenSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhTrang", DbType="NVarChar(50)")]
		public string tinhTrang
		{
			get
			{
				return this._tinhTrang;
			}
			set
			{
				if ((this._tinhTrang != value))
				{
					this.OntinhTrangChanging(value);
					this.SendPropertyChanging();
					this._tinhTrang = value;
					this.SendPropertyChanged("tinhTrang");
					this.OntinhTrangChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
